[package]
name = "mining-game"
version = "0.1.0"
edition = "2021"


[dependencies]
bevy = { version = "0.6.0"}
dolly = "0.1"
once_cell = "1.9"
parry3d = "0.8"
k = "0.27"
nalgebra ={ version =  "0.30", features = ["glam020"] }

